services:
  mysql:
    image: mysql:8.0
    container_name: nexa-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nexa_bank
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data_prod:/var/lib/mysql
    networks:
      - nexa-network-prod
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexa-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/nexa_bank"
      PORT: 3001
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - nexa-network-prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexa-frontend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.tudominio.com
    depends_on:
      - backend
    networks:
      - nexa-network-prod

volumes:
  mysql_data_prod:
    driver: local

networks:
  nexa-network-prod:
    driver: bridge