version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nexa-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexa_banking
      MYSQL_USER: nexa_user
      MYSQL_PASSWORD: nexa_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./sql/dml.sql:/docker-entrypoint-initdb.d/dml.sql
    networks:
      - nexa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Aplicación Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nexa-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://nexa_user:nexa_password@mysql:3306/nexa_banking
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - nexa-network
    command: npm run start:dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nexa-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
    depends_on:
      - mysql
    networks:
      - nexa-network

volumes:
  mysql_data:

networks:
  nexa-network:
    driver: bridge